 //<auto-generated>
// Well, not really. This is just a trick to get StyleCop off my back.
// </auto-generated>
namespace QuizHut.Web.Areas.Identity.Pages.Account.Manage
{
    using System.ComponentModel.DataAnnotations;
    using System.Text;
    using System.Text.Encodings.Web;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Identity.UI.Services;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using Microsoft.AspNetCore.WebUtilities;
    using QuizHut.Data.Models;
    using QuizHut.Web.Infrastructure.Filters;

    [OverrideDefoultLayoutPageFilter]
    public partial class EmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IEmailSender emailSender;

        public EmailModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailSender emailSender)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.emailSender = emailSender;
        }

        public string Username { get; set; }

        public string Email { get; set; }

        public bool IsEmailConfirmed { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "New email")]
            public string NewEmail { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return this.Redirect("/");
        }

        public IActionResult OnPostAsync()
        {
            return this.Redirect("/");
        }

        public IActionResult OnPostSendVerificationEmailAsync()
        {
            return this.Redirect("/");
        }

        private IActionResult LoadAsync(ApplicationUser user)
        {
            return this.Redirect("/");
        }
    }
}
