 //<auto-generated>
// Well, not really. This is just a trick to get StyleCop off my back.
// </auto-generated>
namespace QuizHut.Web.Areas.Identity.Pages.Account.Manage
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;
    using QuizHut.Data.Models;
    using QuizHut.Web.Infrastructure.Filters;

    [OverrideDefoultLayoutPageFilter]
    public partial class IndexModel : PageModel
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public IndexModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public string Username { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Phone]
            [Display(Name = "Phone number")]
            public string PhoneNumber { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return this.Redirect("/");
        }

        public IActionResult OnPostAsync()
        {
            return this.Redirect("/");
        }
    }
}
